# Generated by Django 3.1.7 on 2021-03-14 09:14

import API_Diagnosis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image_record', models.ImageField(blank=True, null=True, upload_to=API_Diagnosis.models.upload_path)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='1', max_length=20)),
                ('anatom_site_general_challenge', models.CharField(choices=[('abdoben', 'abdoben'), ('back', 'back'), ('chest', 'chest'), ('ear', 'ear'), ('face', 'face'), ('foot', 'foot'), ('hand', 'hand'), ('head/neck', 'head/neck'), ('torsor', 'torsor'), ('palms/soles', 'palms/soles'), ('upper extremity', 'upper extremity'), ('lower extremity', 'lower extremity')], default='unknown', max_length=256)),
                ('age_approx', models.IntegerField()),
                ('predict', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
