# Generated by Django 3.1.7 on 2021-03-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='user_id',
        ),
    ]
