# Generated by Django 3.1.7 on 2021-03-14 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API_Diagnosis', '0002_remove_diagnosisrecord_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='token',
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DRecord_of_author', to='API_Source.user'),
            preserve_default=False,
        ),
    ]
