# Generated by Django 3.1.7 on 2021-03-07 06:31

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(default='Body_article', null=True)),
                ('status_ar', models.CharField(choices=[('approve', 'approved'), ('pending', 'pending'), ('reject', 'rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cat', models.TextField()),
                ('total_article', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_cmt', models.DateTimeField(default=datetime.datetime(2021, 3, 7, 13, 31, 44, 719975))),
                ('content_cmt', ckeditor.fields.RichTextField(blank=True, default='Body_comment', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(max_length=255)),
                ('privacy_group', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rp', models.CharField(choices=[('Nudity', 'Nudity'), ('Violence', 'Violence'), ('Spam', 'Spam'), ('Hate Speech', 'Hate Speech'), ('Terrorism', 'Terrorism'), ('Something Else', 'Something Else')], default='Something Else', max_length=50)),
                ('warning_level', models.IntegerField()),
                ('action_to_handle', models.CharField(choices=[('remove', 'removed'), ('notification', 'notification'), ('reject', 'rejected')], default='notification', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_processing', models.CharField(choices=[('approve', 'approved'), ('pending', 'pending'), ('reject', 'rejected')], default='pending', max_length=20)),
                ('article_be_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_be_reported', to='API_Article.article')),
            ],
        ),
    ]
