# Generated by Django 3.1.7 on 2021-03-07 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Article', '0002_auto_20210307_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date_cmt',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 13, 38, 41, 540045)),
        ),
    ]
