# Generated by Django 3.1.7 on 2021-03-11 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Article', '0005_auto_20210311_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date_cmt',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 18, 32, 40, 127159)),
        ),
    ]
