# Generated by Django 3.1.7 on 2021-05-16 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Article', '0037_auto_20210430_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date_cmt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 19, 55, 52, 122430)),
        ),
    ]
