# Generated by Django 3.1.7 on 2021-05-16 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Article', '0038_auto_20210516_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date_cmt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 20, 12, 25, 753010)),
        ),
    ]
