# Generated by Django 3.1.7 on 2021-05-21 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Article', '0040_auto_20210516_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetail',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 22, 56, 6, 695057)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date_cmt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 22, 56, 6, 694085)),
        ),
    ]
