# Generated by Django 3.1.7 on 2021-05-22 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Article', '0043_auto_20210521_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date_cmt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 14, 30, 35, 310544)),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
