# Generated by Django 3.1.7 on 2021-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
