# Generated by Django 3.1.7 on 2021-05-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Source', '0002_auto_20210307_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
