# Generated by Django 3.1.7 on 2021-05-16 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Source', '0003_auto_20210516_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='avatar'),
            preserve_default=False,
        ),
    ]
