# Generated by Django 3.1.7 on 2021-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Source', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Can Tho', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0348387208', max_length=11),
        ),
    ]
