# Generated by Django 3.1.7 on 2021-05-22 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Source', '0005_auto_20210516_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Followed',
            field=models.ManyToManyField(blank=True, related_name='_user_Followed_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
